#!/bin/bash
cd "$(git rev-parse --show-toplevel)"
if git diff --cached --name-only | grep -q "slides/slides.md"; then
    prettier slides/slides.md -w
    marp slides/slides.md -o slides/slides.pdf --allow-local-files
    git add slides/slides.md slides/slides.pdf
fi
