#!/bin/bash
cd "$(git rev-parse --show-toplevel)"
prettier slides.md -w
git add slides.md
if git diff --cached --name-only | grep -q "slides.md"; then
    marp slides.md -o slides.pdf
	git add slides.pdf
fi
